version: "3.8"

services:
  postgres:
    image: postgres:17.5
    container_name: postgres_dicetale
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      # Persistência dos dados
      - ./pgdata:/var/lib/postgresql/data
      # Script de inicialização
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    restart: always
  