version: "3.8"

services:
  frontend:
    build: ./Front-End-Dice-Tales
    container_name: dicetale_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./Dice-Tale-Backend
    container_name: dicetale_backend
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    restart: always

  postgres:
    image: postgres:17.5
    container_name: postgres_dicetale
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # Persistência dos dados
      - pgdata:/var/lib/postgresql/data
      # Script de inicialização
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    restart: always
  
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
  pgdata:

  